MobileSensingServer/config/routes.rb
MobileSensors::Application.routes.draw do
  devise_for :users, :controllers => {sessions: 'sessions'}

  resources :rotation_vectors

  resources :proximities

  resources :pressures

  resources :magnetic_fields

  resources :locations

  resources :linear_accelerations

  resources :lights

  resources :gyroscopes

  resources :gravities

  resources :batteries

  resources :annotations

  resources :accelerometers

  resources :recordings

  resources :devices

  ['accelerometers', 'annotations', 'batteries', 'gyroscopes', 'recordings', 'devices', 'gravities', 'lights', 'linear_accelerations', 'locations', 'magnetic_fields', 'pressures', 'proximities', 'rotation_vectors'].each do |controller|
    get controller + '/recording/:id' => controller + '#show_highcharts'
    get 'recording/:id/' + controller => controller + '#list'
  end

  get 'admin/sensor-upload/list' => 'admin#sensor_upload_list'
  get 'admin/sensor-upload/:id/raw' => 'admin#sensor_upload_data'
  get 'admin/sensor-upload/:id/import' => 'admin#sensor_upload_import'
  get 'admin/user/list' => 'admin#user_list'

  post 'recordings/upload' => 'recordings#upload'
  get 'user/device/:id' => 'recordings#list'
  get 'user/device' => 'recordings#list'
  root 'recordings#list'

  

end

MobileSensingServer/app/models/recording.rb
class Recording < ActiveRecord::Base

  self.per_page = 10

  #default_scope :order => 'time_start DESC'

  belongs_to :device
  belongs_to :user

  has_many :accelerometers, :dependent => :delete_all, :order => 'time ASC'
  has_many :annotations, :dependent => :delete_all, :order => 'time ASC'
  has_many :batteries, :dependent => :delete_all, :order => 'time ASC'
  has_many :gravities, :dependent => :delete_all, :order => 'time ASC'
  has_many :gyroscopes, :dependent => :delete_all, :order => 'time ASC'
  has_many :lights, :dependent => :delete_all, :order => 'time ASC'
  has_many :linear_accelerations, :dependent => :delete_all, :order => 'time ASC'
  has_many :locations, :dependent => :delete_all, :order => 'time ASC'
  has_many :magnetic_fields, :dependent => :delete_all, :order => 'time ASC'
  has_many :pressures, :dependent => :delete_all, :order => 'time ASC'
  has_many :proximities, :dependent => :delete_all, :order => 'time ASC'
  has_many :rotation_vectors, :dependent => :delete_all, :order => 'time ASC'

  accepts_nested_attributes_for :accelerometers
  accepts_nested_attributes_for :annotations
  accepts_nested_attributes_for :batteries
  accepts_nested_attributes_for :gravities
  accepts_nested_attributes_for :gyroscopes
  accepts_nested_attributes_for :lights
  accepts_nested_attributes_for :linear_accelerations
  accepts_nested_attributes_for :locations
  accepts_nested_attributes_for :magnetic_fields
  accepts_nested_attributes_for :pressures
  accepts_nested_attributes_for :proximities
  accepts_nested_attributes_for :rotation_vectors
  
  def get_duration
    return nil if self.time_start.nil?
    return nil if self.time_stop.nil?
    time_difference = Time.diff(self.time_start, self.time_stop, '%y, %d and %h:%m:%s')[:diff]
  end

  def classify
    Rjb::load('/home/lukas/projects/uni/forschungspraktikum/MobileSensors.jar', ['-verbose:gc'])
    loc = Rjb::import('MobileSensors.Storage.GPS.Location')
    l = loc.new(1,2,3,4,5,6,7)
    l.getTime()
  end

  def upload(line)
    entry = JSON.parse(line)

    if entry.has_key?('sensor') then
    self.upload_sensor(entry)
    return
    end

    if entry.has_key?('annotation') then
      a = Annotation.new 
      a.recording = self
      a.upload(entry['annotation']['time'], entry['annotation']['value'])
    return
    end

    if entry.has_key?('location') then
      l = Location.new
      l.recording = self
      l.upload(entry['location']['time'], entry['location'])
    return
    end

    if entry.has_key?('rec') then
      if entry['rec'].has_key?('did') then
        d = Device.find_or_create_by(:identifier => entry['rec']['did'])
        self.device = d
      end
      if entry['rec'].has_key?('title') then
        self.title = entry['rec']['title']
      end
      if entry['rec'].has_key?('time_start') then
        self.time_start = Time.strptime(entry['rec']['time_start'].to_s, '%Q')
      end
      if entry['rec'].has_key?('time_stop') then
        self.time_stop = Time.strptime(entry['rec']['time_stop'].to_s, '%Q')
      end
    self.save
    return
    end
  end

  def upload_sensor(entry)
    case entry['sensor']['sensor']
    when 1
      a = Accelerometer.new
      a.recording = self
      a.upload(entry['sensor']['time'], entry['sensor']['values'])
    when 2
      m = MagneticField.new
      m.recording =  self
      m.upload(entry['sensor']['time'], entry['sensor']['values'])
    when 4
      g = Gyroscope.new
      g.recording = self
      g.upload(entry['sensor']['time'], entry['sensor']['values'])
    when 5
      l = Light.new
      l.recording = self
      l.upload(entry['sensor']['time'], entry['sensor']['values'])
    when 6
      p = Pressure.new
      p.recording = self
      p.upload(entry['sensor']['time'], entry['sensor']['values'])
    when 8
      p = Proximity.new
      p.recording = self
      p.upload(entry['sensor']['time'], entry['sensor']['values'])
    when 9
      g = Gravity.new
      g.recording = self
      g.upload(entry['sensor']['time'], entry['sensor']['values'])
    when 10
      l = LinearAcceleration.new
      l.recording = self
      l.upload(entry['sensor']['time'], entry['sensor']['values'])
    when 11
      r = RotationVector.new
      r.recording = self
      r.upload(entry['sensor']['time'], entry['sensor']['values'])
    end
  end

end

MobileSensingServer/app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  before_action :set_recording, only: [:show, :edit, :update, :destroy]
  before_filter :handle_gzip_params

  # GET /recordings
  # GET /recordings.json
  def index
    respond_to do |format|
        format.html { @recordings = Recording.all.paginate(:page => params[:page]) }
        format.json { @recordings = Recording.all }
    end    

  end

  def list 
    @user = current_user
    if @user.devices.count <= 0 then
	@device = nil
   	return
    end
    if params[:id].nil? then
     	@device = @user.devices.first
    else  
	@device = Device.find(params[:id])
    end
    @recordings = @device.recordings.paginate(:page => params[:page])
  end

  # GET /recordings/1
  # GET /recordings/1.json
  def show
  end

  # GET /recordings/new
  def new
    @recording = Recording.new
  end

  # GET /recordings/1/edit
  def edit
  end

  # POST /recordings
  # POST /recordings.json
  def create
    @recording = Recording.new(recording_params)

    respond_to do |format|
      if @recording.save
        format.html { redirect_to @recording, notice: 'Recording was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recording }
      else
        format.html { render action: 'new' }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recordings/1
  # PATCH/PUT /recordings/1.json
  def update
    respond_to do |format|
      if @recording.update(recording_params)
        format.html { redirect_to @recording, notice: 'Recording was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recordings/1
  # DELETE /recordings/1.json
  def destroy
    @recording.destroy
    respond_to do |format|
      format.html { redirect_to recordings_url, notice: 'Recording was successfully deleted'  }
      format.json { head :no_content }
    end
  end

  def upload
    
    upload = SensorUpload.new
    upload.user = current_user
    upload.data = request.raw_post
    upload.save
    
    upload.delay.store_data
    
   render :nothing => true
  end
  
  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recording
    @recording = Recording.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def recording_params
    params.require(:recording).permit(:device_id, :title,
    :accelerometers_attributes => [:recording_id, :time, :x, :y, :z],
    :annotations_attributes => [:recording_id, :time, :value],
    :batteries_attributes => [:recording_id, :time, :level, :scale],
    :devices_attributes => [:identifier],
    :gravities_attributes => [:recording_id, :time, :x, :y, :z],
    :gyroscopes_attributes => [:recording_id, :time, :rX, :rY, :rZ],
    :lights_attributes => [:recording_id, :time, :ambientLight],
    :linear_accelerations_attributes => [:recording_id, :time, :x, :y, :z],
    :locations_attributes => [:time, :longitude, :latitude, :altitude, :speed, :bearing, :accuracy],
    :magnetic_fields_attributes => [:recording_id, :time, :x, :y, :z],
    :pressures_attributes => [:recording_id, :time, :pressure],
    :proximities_attributes => [:recording_id, :time, :proximity],
    :rotation_vectors_attributes => [:recording_id, :time, :xSinTheta, :ySinTheta, :zSinTheta])
  end
end

MobileSensingServer/app/helpers/recordings_helper.rb
module RecordingsHelper
end

MobileSensingServer/app/views/recordings/_annotations.html.erb
<%= render :partial => '/annotations/table', :locals => {:annotations => recording.annotations} %>
<%= link_to 'New Annotation', new_annotation_path %>

MobileSensingServer/app/views/recordings/_charts.html.erb
<% ['accelerometers', 'batteries', 'gravities', 'gyroscopes', 'lights', 'linear_accelerations', 'locations', 'magnetic_fields', 'pressures', 'proximities', 'rotation_vectors'].each do |sensor|%>
<% if (eval('recording.' + sensor).count > 0)%>
<div class="panel panel-default">
	<div class="panel-heading">
		<h4 class="panel-title"><%= sensor %></h4>
	</div>
	<div class="panel-body">
		<%= eval("render :partial =>'" + sensor + "/chart' , :locals => {:" + sensor + " => recording." + sensor + "}") %>
	</div>
</div>
<% end %>
<% end %>

MobileSensingServer/app/views/recordings/_form.html.erb
<%= form_for(@recording) do |f| %>
  <% if @recording.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recording.errors.count, "error") %> prohibited this recording from being saved:</h2>

      <ul>
      <% @recording.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br />
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => 'form-control', :style => 'width:250px;' %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-default' %>
  </div>
<% end %>

MobileSensingServer/app/views/recordings/_map.html.erb
<% if (recording.locations.count > 0)%>
<%= render :partial => 'locations/map', :locals => {:locations => recording.locations} %>
<% else %>
No locations were recorded.
<% end %>

MobileSensingServer/app/views/recordings/_overview.html.erb
<span class="glyphicon glyphicon-calendar"></span> <b><%= recording.time_start.strftime("%Y-%m-%d %H:%M") unless recording.time_start.nil?%></b>
<br />
<span class="glyphicon glyphicon-time"></span> <b><%= recording.get_duration %> (hh:mm:ss)</b>
<br />
<span class="glyphicon glyphicon-user"></span> <b><%= recording.user.email unless recording.user.nil? %></b>
<br />
<span class="glyphicon glyphicon-comment"></span> <b><%= recording.title %></b>
<br />
<span class="glyphicon glyphicon-phone"></span> <%= link_to(recording.device.identifier, device_path(recording.device)) unless recording.device.nil? %>

MobileSensingServer/app/views/recordings/_sensors.html.erb
<table class="table table-striped">
	<tr>
		<th>Sensor</th>
		<th>Available</th>
		<th>Samples</th>
		<th><p class="text-right">Hz</p></th>
		<th><p class="text-right">CSV</p></th>
	</tr>
	<% ['accelerometers', 'annotations', 'batteries', 'gravities', 'gyroscopes', 'lights', 'linear_accelerations', 'locations', 'magnetic_fields', 'pressures', 'proximities', 'rotation_vectors'].each do |sensor|%>
	<tr>
		<td><%= sensor %></td>
		<td><div class="pull-left"><% if eval('recording.' + sensor).count > 0 then %><span class="glyphicon glyphicon-ok"></span><% end %></div></td>
		<td><%= eval('recording.' + sensor).count %></td>
		<td><p class="text-right"><%= eval('recording.' + sensor).get_hz.to_s %> Hz</p></td>
		<td><div class="pull-right"><%= render :partial => "shared/link_button", :locals => { link: '/recording/' + recording.id.to_s + '/' + sensor + '.csv', caption:'download', icon:'download'} %></div></td>
	</tr>
	<% end %>
</table>

MobileSensingServer/app/views/recordings/_table.html.erb
<table class="table table-striped">
        <tr>
                <th>Start Time</th>
                <th>Duration (hh:mm:ss)</th>
                <th>Title</th>
                <th></th>
                <th></th>
                <th></th>
<% if extended then %>
                <th>User</th>
                <th>Device</th>
<% end %>
        </tr>

        <% recordings.each do |recording| %>
        <tr>
                <td><span class="glyphicon glyphicon-calendar"></span> <%= recording.time_start.strftime("%Y-%m-%d %H:%M") unless recording.time_start.nil? %></td>
                <td><span class="glyphicon glyphicon-time"></span> <% if recording.get_duration.nil? then %>0<% else %><%= recording.get_duration %><% end %></td>
                <td><span class="glyphicon glyphicon-comment"></span> <%= recording.title %></td>
                <td><%= render :partial => "shared/link_button", :locals => { link: recording_path(recording), caption:'Overview', icon:'list'} %></td>
                <td><%= render :partial => "shared/link_button", :locals => { link: edit_recording_path(recording), caption:'Edit', icon:'edit'} %></td>
                <td><%= render :partial => "shared/link_button", :locals => { link: recording_path(recording), caption:'Delete', icon:'trash', confirm: true, method:'delete'} %></td>
<% if extended then %>
                <td><span class="glyphicon glyphicon-user"></span> <%= recording.user.email unless recording.user.nil? %></td>
                <td><span class="glyphicon glyphicon-phone"></span> <%= link_to(recording.device.identifier, device_path(recording.device)) unless recording.device.nil? %></td>
<% end %>
        </tr>
        <% end %>
</table>

MobileSensingServer/app/views/recordings/edit.html.erb
<h1>Editing recording</h1>

<%= render 'form' %>

MobileSensingServer/app/views/recordings/index.html.erb
<h4>Recordings</h4>

<%= render :partial => 'table', :locals => {:recordings => @recordings, :extended => true} %>

<%= will_paginate @recordings %>

MobileSensingServer/app/views/recordings/list.html.erb
<% if (@device == nil) then %>
No Devices
<% else %>
<h4 class="pull-right">Devices</h4>

<ul class="nav nav-tabs">
        <% @user.devices.each do |device| %>
                <li <% if(@device == device) then %>class="active"<% end %>>
                        <a href="/user/device/<%= device.id %>">
                                <span class="glyphicon glyphicon-phone"></span>
                                <span class="badge pull-right"><%= device.recordings.count %></span>
                                <%= device.identifier %>&nbsp;
                        </a>
                </li>
        <% end %>
</ul>

<br />
<h4>Recordings</h4>

<%= render :partial => 'table', :locals => {:recordings => @recordings, :extended => false} %>

<%= will_paginate @recordings %>

<% end %>

MobileSensingServer/app/views/recordings/new.html.erb
<h1>New recording</h1>

<%= render 'form' %>

<%= link_to 'Back', recordings_path %>

MobileSensingServer/app/views/recordings/show.html.erb
<h1>Recording <small><%= link_to 'Edit', edit_recording_path(@recording) %></small></h1>
<br />
<div class="row">
	<div class="col-md-10">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"> <span class="glyphicon glyphicon-chevron-down"></span> Annotations <span class="badge pull-right"><%= @recording.annotations.count%></span> </h4>
				</a>
			</div>
			<div id="collapseTwo" class="panel-collapse collapse">
				<div class="panel-body">
					<%= render :partial => 'annotations', :locals => {:recording => @recording} %>
				</div>
			</div>
		</div>

		<br />

		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"> <span class="glyphicon glyphicon-chevron-down"></span> Sensors</h4>
				</a>
			</div>
			<div id="collapseOne" class="panel-collapse collapse">
				<div class="panel-body">
					<%= render :partial => 'sensors', :locals => {:recording => @recording} %>
				</div>
			</div>
		</div >
	</div>
	<div class="col-md-2">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">Details</h4>
			</div>
			<div class="panel-body">
				<%= render :partial => 'overview', :locals => {:recording => @recording} %>
			</div>
		</div>
	</div>
</div>

<br />

<div class="panel panel-default">
	<div class="panel-heading">
		<h4 class="panel-title">Locations</h4>
	</div>
	<div class="panel-body">
		<%= render :partial => 'map', :locals => {:recording => @recording} %>
	</div>
</div>

<br />

<%= render :partial => 'charts', :locals => {:recording => @recording} %>