MobileSensingServer/config/routes.rb
MobileSensors::Application.routes.draw do
  devise_for :users, :controllers => {sessions: 'sessions'}

  resources :rotation_vectors

  resources :proximities

  resources :pressures

  resources :magnetic_fields

  resources :locations

  resources :linear_accelerations

  resources :lights

  resources :gyroscopes

  resources :gravities

  resources :batteries

  resources :annotations

  resources :accelerometers

  resources :recordings

  resources :devices

  ['accelerometers', 'annotations', 'batteries', 'gyroscopes', 'recordings', 'devices', 'gravities', 'lights', 'linear_accelerations', 'locations', 'magnetic_fields', 'pressures', 'proximities', 'rotation_vectors'].each do |controller|
    get controller + '/recording/:id' => controller + '#show_highcharts'
    get 'recording/:id/' + controller => controller + '#list'
  end

  get 'admin/sensor-upload/list' => 'admin#sensor_upload_list'
  get 'admin/sensor-upload/:id/raw' => 'admin#sensor_upload_data'
  get 'admin/sensor-upload/:id/import' => 'admin#sensor_upload_import'
  get 'admin/user/list' => 'admin#user_list'

  post 'recordings/upload' => 'recordings#upload'
  get 'user/device/:id' => 'recordings#list'
  get 'user/device' => 'recordings#list'
  root 'recordings#list'

  

end

MobileSensingServer/app/models/linear_acceleration.rb
class LinearAcceleration < ActiveRecord::Base
  belongs_to :recording
  include Sensor

  def upload(time, values)
    self.time = Time.strptime(time.to_s, '%Q')
    self.x = values[0]
    self.y = values[1]
    self.z = values[2]
    self.save
  end
  
end

MobileSensingServer/app/controllers/linear_accelerations_controller.rb
class LinearAccelerationsController < ApplicationController
  before_action :set_linear_acceleration, only: [:show, :edit, :update, :destroy]

  # GET /linear_accelerations
  # GET /linear_accelerations.json
  def index
    @linear_accelerations = LinearAcceleration.all
  end

  # GET /linear_accelerations/1
  # GET /linear_accelerations/1.json
  def show
  end

  # GET /linear_accelerations/new
  def new
    @linear_acceleration = LinearAcceleration.new
  end

  # GET /linear_accelerations/1/edit
  def edit
  end

  # POST /linear_accelerations
  # POST /linear_accelerations.json
  def create
    @linear_acceleration = LinearAcceleration.new(linear_acceleration_params)

    respond_to do |format|
      if @linear_acceleration.save
        format.html { redirect_to @linear_acceleration, notice: 'Linear acceleration was successfully created.' }
        format.json { render action: 'show', status: :created, location: @linear_acceleration }
      else
        format.html { render action: 'new' }
        format.json { render json: @linear_acceleration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /linear_accelerations/1
  # PATCH/PUT /linear_accelerations/1.json
  def update
    respond_to do |format|
      if @linear_acceleration.update(linear_acceleration_params)
        format.html { redirect_to @linear_acceleration, notice: 'Linear acceleration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @linear_acceleration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /linear_accelerations/1
  # DELETE /linear_accelerations/1.json
  def destroy
    @linear_acceleration.destroy
    respond_to do |format|
      format.html { redirect_to linear_accelerations_url }
      format.json { head :no_content }
    end
  end

  def list
    recording = Recording.find(params[:id])
    @linear_accelerations = recording.linear_accelerations
  end
  
  def show_highcharts
    recording = Recording.find(params[:id])
    @sensors = recording.linear_accelerations.sample_down(params[:begin], params[:end])
    super
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_linear_acceleration
      @linear_acceleration = LinearAcceleration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def linear_acceleration_params
      params.require(:linear_acceleration).permit(:recording_id, :time, :x, :y, :z)
    end
end

MobileSensingServer/app/helpers/linear_accelerations_helper.rb
module LinearAccelerationsHelper
end

MobileSensingServer/app/views/linear_accelerations/_chart.html.erb
<%= render :partial => 'shared/highcharts_lazy_loading', :locals => { :sensors => linear_accelerations, :attributes => ['x', 'y', 'z'], :unit => 'm/s²', :caption => 'linear_accelerations' } %>

MobileSensingServer/app/views/linear_accelerations/_form.html.erb
<%= form_for(@linear_acceleration) do |f| %>
  <% if @linear_acceleration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@linear_acceleration.errors.count, "error") %> prohibited this linear_acceleration from being saved:</h2>

      <ul>
      <% @linear_acceleration.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recording %><br>
    <%= f.text_field :recording %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :x %><br>
    <%= f.text_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br>
    <%= f.text_field :y %>
  </div>
  <div class="field">
    <%= f.label :z %><br>
    <%= f.text_field :z %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MobileSensingServer/app/views/linear_accelerations/edit.html.erb
<h1>Editing linear_acceleration</h1>

<%= render 'form' %>

<%= link_to 'Show', @linear_acceleration %> |
<%= link_to 'Back', linear_accelerations_path %>

MobileSensingServer/app/views/linear_accelerations/index.html.erb
<h1>Listing linear_accelerations</h1>

<table>
  <thead>
    <tr>
      <th>Recording</th>
      <th>Time</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @linear_accelerations.each do |linear_acceleration| %>
      <tr>
        <td><%= linear_acceleration.recording %></td>
        <td><%= linear_acceleration.time %></td>
        <td><%= linear_acceleration.x %></td>
        <td><%= linear_acceleration.y %></td>
        <td><%= linear_acceleration.z %></td>
        <td><%= link_to 'Show', linear_acceleration %></td>
        <td><%= link_to 'Edit', edit_linear_acceleration_path(linear_acceleration) %></td>
        <td><%= link_to 'Destroy', linear_acceleration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Linear acceleration', new_linear_acceleration_path %>

MobileSensingServer/app/views/linear_accelerations/list.csv.erb
time,x,y,z
<% @linear_accelerations.each do |b|%>
<%= b.get_milliseconds%>,<%= b.x %>,<%= b.y %>,<%= b.z %>
<% end %>

MobileSensingServer/app/views/linear_accelerations/new.html.erb
<h1>New linear_acceleration</h1>

<%= render 'form' %>

<%= link_to 'Back', linear_accelerations_path %>

MobileSensingServer/app/views/linear_accelerations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recording:</strong>
  <%= @linear_acceleration.recording %>
</p>

<p>
  <strong>Time:</strong>
  <%= @linear_acceleration.time %>
</p>

<p>
  <strong>X:</strong>
  <%= @linear_acceleration.x %>
</p>

<p>
  <strong>Y:</strong>
  <%= @linear_acceleration.y %>
</p>

<p>
  <strong>Z:</strong>
  <%= @linear_acceleration.z %>
</p>

<%= link_to 'Edit', edit_linear_acceleration_path(@linear_acceleration) %> |
<%= link_to 'Back', linear_accelerations_path %>