MobileSensingServer/config/routes.rb
MobileSensors::Application.routes.draw do
  devise_for :users, :controllers => {sessions: 'sessions'}

  resources :rotation_vectors

  resources :proximities

  resources :pressures

  resources :magnetic_fields

  resources :locations

  resources :linear_accelerations

  resources :lights

  resources :gyroscopes

  resources :gravities

  resources :batteries

  resources :annotations

  resources :accelerometers

  resources :recordings

  resources :devices

  ['accelerometers', 'annotations', 'batteries', 'gyroscopes', 'recordings', 'devices', 'gravities', 'lights', 'linear_accelerations', 'locations', 'magnetic_fields', 'pressures', 'proximities', 'rotation_vectors'].each do |controller|
    get controller + '/recording/:id' => controller + '#show_highcharts'
    get 'recording/:id/' + controller => controller + '#list'
  end

  get 'admin/sensor-upload/list' => 'admin#sensor_upload_list'
  get 'admin/sensor-upload/:id/raw' => 'admin#sensor_upload_data'
  get 'admin/sensor-upload/:id/import' => 'admin#sensor_upload_import'
  get 'admin/user/list' => 'admin#user_list'

  post 'recordings/upload' => 'recordings#upload'
  get 'user/device/:id' => 'recordings#list'
  get 'user/device' => 'recordings#list'
  root 'recordings#list'

  

end

MobileSensingServer/app/models/light.rb
class Light < ActiveRecord::Base
  belongs_to :recording
  include Sensor

  def upload(time, values)
    self.time = Time.strptime(time.to_s, '%Q')
    self.ambientLight = values[0]
    self.save
  end

end

MobileSensingServer/app/controllers/lights_controller.rb
class LightsController < ApplicationController
  before_action :set_light, only: [:show, :edit, :update, :destroy]

  # GET /lights
  # GET /lights.json
  def index
    @lights = Light.all
  end

  # GET /lights/1
  # GET /lights/1.json
  def show
  end

  # GET /lights/new
  def new
    @light = Light.new
  end

  # GET /lights/1/edit
  def edit
  end

  # POST /lights
  # POST /lights.json
  def create
    @light = Light.new(light_params)

    respond_to do |format|
      if @light.save
        format.html { redirect_to @light, notice: 'Light was successfully created.' }
        format.json { render action: 'show', status: :created, location: @light }
      else
        format.html { render action: 'new' }
        format.json { render json: @light.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lights/1
  # PATCH/PUT /lights/1.json
  def update
    respond_to do |format|
      if @light.update(light_params)
        format.html { redirect_to @light, notice: 'Light was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @light.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lights/1
  # DELETE /lights/1.json
  def destroy
    @light.destroy
    respond_to do |format|
      format.html { redirect_to lights_url }
      format.json { head :no_content }
    end
  end

  def list
    recording = Recording.find(params[:id])
    @lights = recording.lights
  end

  def show_highcharts
    recording = Recording.find(params[:id])
    @sensors = recording.lights.sample_down(params[:begin], params[:end])
    super
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_light
      @light = Light.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def light_params
      params.require(:light).permit(:recording_id, :time, :ambientLight)
    end
end

MobileSensingServer/app/helpers/lights_helper.rb
module LightsHelper
end

MobileSensingServer/app/views/lights/_chart.html.erb
<%= render :partial => 'shared/highcharts_lazy_loading', :locals => { :sensors => lights, :attributes => ['ambientLight'], :unit => 'candela', :caption => 'lights' } %>

MobileSensingServer/app/views/lights/_form.html.erb
<%= form_for(@light) do |f| %>
  <% if @light.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@light.errors.count, "error") %> prohibited this light from being saved:</h2>

      <ul>
      <% @light.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recording %><br>
    <%= f.text_field :recording %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :ambientLight %><br>
    <%= f.text_field :ambientLight %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MobileSensingServer/app/views/lights/edit.html.erb
<h1>Editing light</h1>

<%= render 'form' %>

<%= link_to 'Show', @light %> |
<%= link_to 'Back', lights_path %>

MobileSensingServer/app/views/lights/index.html.erb
<h1>Listing lights</h1>

<table>
  <thead>
    <tr>
      <th>Recording</th>
      <th>Time</th>
      <th>Ambientlight</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lights.each do |light| %>
      <tr>
        <td><%= light.recording %></td>
        <td><%= light.time %></td>
        <td><%= light.ambientLight %></td>
        <td><%= link_to 'Show', light %></td>
        <td><%= link_to 'Edit', edit_light_path(light) %></td>
        <td><%= link_to 'Destroy', light, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Light', new_light_path %>

MobileSensingServer/app/views/lights/list.csv.erb
time,ambientLight
<% @lights.each do |b|%>
<%= b.get_milliseconds %>,<%= b.ambientLight %>
<% end %>

MobileSensingServer/app/views/lights/new.html.erb
<h1>New light</h1>

<%= render 'form' %>

<%= link_to 'Back', lights_path %>

MobileSensingServer/app/views/lights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recording:</strong>
  <%= @light.recording %>
</p>

<p>
  <strong>Time:</strong>
  <%= @light.time %>
</p>

<p>
  <strong>Ambientlight:</strong>
  <%= @light.ambientLight %>
</p>

<%= link_to 'Edit', edit_light_path(@light) %> |
<%= link_to 'Back', lights_path %>