MobileSensingServer/config/routes.rb
MobileSensors::Application.routes.draw do
  devise_for :users, :controllers => {sessions: 'sessions'}

  resources :rotation_vectors

  resources :proximities

  resources :pressures

  resources :magnetic_fields

  resources :locations

  resources :linear_accelerations

  resources :lights

  resources :gyroscopes

  resources :gravities

  resources :batteries

  resources :annotations

  resources :accelerometers

  resources :recordings

  resources :devices

  ['accelerometers', 'annotations', 'batteries', 'gyroscopes', 'recordings', 'devices', 'gravities', 'lights', 'linear_accelerations', 'locations', 'magnetic_fields', 'pressures', 'proximities', 'rotation_vectors'].each do |controller|
    get controller + '/recording/:id' => controller + '#show_highcharts'
    get 'recording/:id/' + controller => controller + '#list'
  end

  get 'admin/sensor-upload/list' => 'admin#sensor_upload_list'
  get 'admin/sensor-upload/:id/raw' => 'admin#sensor_upload_data'
  get 'admin/sensor-upload/:id/import' => 'admin#sensor_upload_import'
  get 'admin/user/list' => 'admin#user_list'

  post 'recordings/upload' => 'recordings#upload'
  get 'user/device/:id' => 'recordings#list'
  get 'user/device' => 'recordings#list'
  root 'recordings#list'

  

end

MobileSensingServer/app/models/gravity.rb
class Gravity < ActiveRecord::Base
  belongs_to :recording
  include Sensor

  def upload(time, values)
    self.time = Time.strptime(time.to_s, '%Q')
    self.x = values[0]
    self.y = values[1]
    self.z = values[2]
    self.save
  end
  
end

MobileSensingServer/app/controllers/gravities_controller.rb
class GravitiesController < ApplicationController
  before_action :set_gravity, only: [:show, :edit, :update, :destroy]

  # GET /gravities
  # GET /gravities.json
  def index
    @gravities = Gravity.all
  end

  # GET /gravities/1
  # GET /gravities/1.json
  def show
  end

  # GET /gravities/new
  def new
    @gravity = Gravity.new
  end

  # GET /gravities/1/edit
  def edit
  end

  # POST /gravities
  # POST /gravities.json
  def create
    @gravity = Gravity.new(gravity_params)

    respond_to do |format|
      if @gravity.save
        format.html { redirect_to @gravity, notice: 'Gravity was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gravity }
      else
        format.html { render action: 'new' }
        format.json { render json: @gravity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gravities/1
  # PATCH/PUT /gravities/1.json
  def update
    respond_to do |format|
      if @gravity.update(gravity_params)
        format.html { redirect_to @gravity, notice: 'Gravity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gravity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gravities/1
  # DELETE /gravities/1.json
  def destroy
    @gravity.destroy
    respond_to do |format|
      format.html { redirect_to gravities_url }
      format.json { head :no_content }
    end
  end
  
  def list
    recording = Recording.find(params[:id])
    @gravities = recording.gravities
  end
  
  def show_highcharts
    recording = Recording.find(params[:id])
    @sensors = recording.gravities.sample_down(params[:begin], params[:end])
    super
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gravity
      @gravity = Gravity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gravity_params
      params.require(:gravity).permit(:recording_id, :time, :x, :y, :z)
    end
end

MobileSensingServer/app/helpers/gravities_helper.rb
module GravitiesHelper
end

MobileSensingServer/app/views/gravities/_chart.html.erb
<%= render :partial => 'shared/highcharts_lazy_loading', :locals => { :sensors => gravities, :attributes => ['x', 'y', 'z'], :unit => 'm/s²', :caption => 'gravities' } %>

MobileSensingServer/app/views/gravities/_form.html.erb
<%= form_for(@gravity) do |f| %>
  <% if @gravity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gravity.errors.count, "error") %> prohibited this gravity from being saved:</h2>

      <ul>
      <% @gravity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recording %><br>
    <%= f.text_field :recording %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :x %><br>
    <%= f.text_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br>
    <%= f.text_field :y %>
  </div>
  <div class="field">
    <%= f.label :z %><br>
    <%= f.text_field :z %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MobileSensingServer/app/views/gravities/edit.html.erb
<h1>Editing gravity</h1>

<%= render 'form' %>

<%= link_to 'Show', @gravity %> |
<%= link_to 'Back', gravities_path %>

MobileSensingServer/app/views/gravities/index.html.erb
<h1>Listing gravities</h1>

<table>
  <thead>
    <tr>
      <th>Recording</th>
      <th>Time</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @gravities.each do |gravity| %>
      <tr>
        <td><%= gravity.recording %></td>
        <td><%= gravity.time %></td>
        <td><%= gravity.x %></td>
        <td><%= gravity.y %></td>
        <td><%= gravity.z %></td>
        <td><%= link_to 'Show', gravity %></td>
        <td><%= link_to 'Edit', edit_gravity_path(gravity) %></td>
        <td><%= link_to 'Destroy', gravity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gravity', new_gravity_path %>

MobileSensingServer/app/views/gravities/list.csv.erb
time,x,y,z
<% @gravities.each do |b|%>
<%= b.get_milliseconds %>,<%= b.x %>,<%= b.y %>,<%= b.z %>
<% end %>

MobileSensingServer/app/views/gravities/new.html.erb
<h1>New gravity</h1>

<%= render 'form' %>

<%= link_to 'Back', gravities_path %>

MobileSensingServer/app/views/gravities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recording:</strong>
  <%= @gravity.recording %>
</p>

<p>
  <strong>Time:</strong>
  <%= @gravity.time %>
</p>

<p>
  <strong>X:</strong>
  <%= @gravity.x %>
</p>

<p>
  <strong>Y:</strong>
  <%= @gravity.y %>
</p>

<p>
  <strong>Z:</strong>
  <%= @gravity.z %>
</p>

<%= link_to 'Edit', edit_gravity_path(@gravity) %> |
<%= link_to 'Back', gravities_path %>